### ISSUE TITLE
Meet error when build and install rocksdb with zenfs enabled

### ISSUE THREAD

**Issue by yingjia-git** [westerndigitalcorporation/zenfs#101]
Hi, I was trying this command:
`sudo DEBUG_LEVEL=0 ROCKSDB_PLUGINS=zenfs make -j48 db_bench install`
But some errors occurred as below:
`$DEBUG_LEVEL is 0
Must specify package names on the command line
Makefile:259: *** pkg-config failed.  Stop.
`
Would anyone give me some advices?

My linux version is 5.10.9.

**Comment by metaspace** [comment]
Hi!

Thanks for reaching out. The issue is caused by facebook/rocksdb#9238. If you use branch [6.27.fb](https://github.com/facebook/rocksdb/tree/6.27.fb) instead of master, it should build.

**Comment by yingjia-git** [comment]
> Hi!
> 
> Thanks for reaching out. The issue is resolved by [facebook/rocksdb#9238](https://github.com/facebook/rocksdb/pull/9238), but that is not merged yet. If you use branch [6.27.fb](https://github.com/facebook/rocksdb/tree/6.27.fb) instead of master, it should build.

It helps, thanks very much!!!
