### ISSUE TITLE
Should we add an UT directory in zenfs repo?

### ISSUE THREAD

**Issue by royguo** [westerndigitalcorporation/zenfs#134]
Current we don't have enough UT to cover all functions, I think we should start working on better UT pipeline

**Comment by metaspace** [comment]
I fully agree. I would suggest Boost.Test as a test harness, since we already include boost in the project.

**Comment by royguo** [comment]
> I fully agree. I would suggest Boost.Test as a test harness, since we already include boost in the project.

Is it possible to reuse RocksDB's gtest?

**Comment by yhr** [comment]
We should try to use whatever rocksdb uses. A while ago I did look into the rocksdb unit testing to extend them for zenfs use, and gtest is a nice framework. Did not have time to add any tests, but now is a good time. @metaspace : do you see any issues using gtest?

**Comment by metaspace** [comment]
@royguo @yhr for sure lets reuse google test if infrastructure is already in place for rocksdb.

**Comment by yhr** [comment]
@royguo  : Do you have a shortlist of test you would like to have?

**Comment by metaspace** [comment]
I started preliminary work on test infrastructure in #172

**Comment by yhr** [comment]
We'll need to rebase and extend the testing framework to make it useful. Let's do that when we add a significant amount of functionality. I've parked the code for now inhttps://github.com/westerndigitalcorporation/zenfs/tree/unit-tests
