### ISSUE TITLE
Better error message when mount of old volume fails

### ISSUE THREAD

**Issue by metaspace** [westerndigitalcorporation/zenfs#141]
The error message given when trying to mount an old ZenFS volume is:
```
Failed creating env: Not implemented: Corruption: ZenFS Superblock: Error: Version missmatch: zenfs://dev:nvme1n1
```

Maybe something like: 
```
The volume uses ZenFS ODF version xx but this ZenFS library requires at least version yy
```
is better. 

@yhr would like to add `"Migrate the data or or switch back to the previously used zenfs version. See documentation at.."`

Related to #118

**Comment by yhr** [comment]
fixed
