### ISSUE TITLE
help wanted: Why the underlying active/open zone limits are so small?

### ISSUE THREAD

**Issue by rpbear88** [westerndigitalcorporation/zenfs#168]
Hi zenfs,

We are considering use ZNS to refactor our storage system, after doing some research we found a fundamental limitation which posed by the NVMe ZNS Active/Open zone count(Maximum Active Resources (MAR) & Maximum Open Resources (MOR)), and the limit on WD's ZNS540 may be only 14.

This should not be a limitation for applications based on znsfs/rocksdb, since only a single thread is able to use the full bandwidth by using/opening only one zone.But for storage systems like us, we have a multi-threading architecture which means every thread hopes to manage it's resource/state within the thread, every thread needs to open some zones, then the underlying limitation will limit how much threads we can have to do application scaling.

I have two questions:
- Why the device/NVMe spec poses such a limitation, what's the root cause of a small limit?
- What's the suggestion for applications like us to do refactor for using ZNS SSD?

**Comment by yhr** [comment]
Hi! Welcome to the community!

The device has limited hardware resources that lead to restrictions on how many zones can be kept active/open simultaneously.

ZenFS allows multiple threads to write to different zones of the drive simultaneously, and this works well. If a lot of threads require simultaneous writes, the active zone resources must be shared. One way of doing this is to send zone append commands from the threads independently and just track the available capacity globally.

Welcome to our chat forum at matrix, we can continue the discussion there if you prefer (otherwise we can use this issue to continue talking)

https://app.element.io/#/room/#zonedstorage-general:matrix.org

**Comment by rpbear88** [comment]
Thanks for your reply, @yhr.

Yes, sharing the zone by multiple threads is a possible solution, but there's at least one disadvantages :if the application only needs to do I/O, it's ok since we can use append semantics without worrying about the concurrency issues, but for some reasons the application will maintain some internal statistics like how many free space can be used in that zone so I can allocate new zones. That will  bring some multi-threading cost for updating such a statistics.

So we prefer to use the thread local design, you mentioned that MAR/MOR is limited by some limited hardware resource, I wonder if it's convenient to disclose what limitations are? In my understanding, the runtime cost of persisting the state like 'write point' should not be so huge, so maybe that limitations come from some static resources?

**Comment by yhr** [comment]
@rpbear88 : Without going into details I can't disclose, the state of each open zone is more than just the write pointer. 

Keeping atomic counters around for tracking remaining zone capacity *should* not be expensive. Let me know if you have any more questions!

**Comment by rpbear88** [comment]
@yhr

Agreed, such a atomic counter should not be the only hurdle to use the sharing solution.But I want to point is that in some case the application design principle is to use all the resource(including disk space) within a thread without sharing with other threads.

I just guess that maybe that  limitation is related with superblock count within the SSD? Say, the number of superblock is limited, and one zone can contain at least superblock, so the zone number is also limited to a small number(depends on superblock/zone size).And if we allow a lots of active zones, then lots of superblock will be occupied at the same time, maybe we'll lack of free superblock to do internal tasks like wear leveling?

So limit the active zone count to be small is reasonable if one zone is able to leverage all the capability of a single SSD.

**Comment by MatiasBjorling** [comment]
On the active zone limitation - one of the primary restrictions is how many "active" contexts that can co-exist. For example, a typical SSD maintains internal ECC (parity) for each zone, which is updated each time the host writes. These need to be maintained somewhere (e.g., controller memory), which then limits how many that can be active.
