### ISSUE TITLE
ZonedBlockDevice::DirectRead and Zone::Append don't handle partial I/O correctly

### ISSUE THREAD

**Issue by jsvaerke** [westerndigitalcorporation/zenfs#181]
In Zone::Append, the pwrite should use left instead of size as the buffer size.
In ZonedBlockDevice::DirectRead, ret is incremented with the bytes read on every read, but the read is always for the full buffer at the same offset, so, e.g., two reads of the first half a buffer will be viewed as a successful read.

**Comment by metaspace** [comment]
Nice catch! Can you submit a PR with a fix?
