### ISSUE TITLE
Remove depenecy on c++17 for terarkdb

### ISSUE THREAD

**Issue by yhr** [westerndigitalcorporation/zenfs#191]
We are using std::filesystem introduced in c++, which is fine for upstream rocksdb which has switched to the new compiler, but terarkdb's users are still on c++11 for now so we need to provide a separate solution for terkarkb.

If we can provide a good solution(removing the need for std::filesystem) that works for both c++11 and c++17, lets move on to that, otherwise we'll need to isolate the use and provide a separate implementation for terarkdb using ifdefs.

**Comment by MatiasBjorling** [comment]
Is there any feedback from the RocksDB folks if they'll begin to use more c++17 features in the upcoming releases? or would it make sense to extract the features in the filesystem c++17 API and not depend on c++17 features for now?

**Comment by metaspace** [comment]
RocksDB are **_requiring_** C++17 now. They have merged a few things that require c++17, see [here](https://github.com/facebook/rocksdb/pulls?q=+%22c%2B%2B+17%22).

I would argue that we  keep targeting c++17 and fall back to boost in case that is not available. We should be able to check the value of ` __cplusplus` to determine what c++ version we are being compiled with.

If TerakDB does not want a dependency on boost, we can implement the stuff by hand. I think it makes more sense to include reviewed code from boost than rolling our own stuff though.

**Comment by royguo** [comment]
For important online services, we don't dare to upgrade the compiler unless we find some critical bugs in older versions. AFAIK, lots of companies are still using RocksDB 5.x. This is because any upgrade could possibly lead to new bugs (from now code), so we prefer STABLE rather than FAST....

**Comment by metaspace** [comment]
> For important online services, we don't dare to upgrade the compiler unless we find some critical bugs in older versions. AFAIK, lots of companies are still using RocksDB 5.x. This is because any upgrade could possibly lead to new bugs (from now code), so we prefer STABLE rather than FAST....

ZenFS 2.x supports RocksDB >= 7, and RocksDB 7 requires a C++17 compiler. The ZenFS 1.x releases are compatible with RocksDB 6 and compiles with a C++11 compiler.

C++17 support was complete in gcc 8.1.0 which was released May 2018 and clang 7.0.0 that was released in September 2018. That is 4 years ago, not really bleeding edge stuff :shrug:

**Comment by yhr** [comment]
Fix merged
