### ISSUE TITLE
No valid superblock found

### ISSUE THREAD

**Issue by lmc395319437** [westerndigitalcorporation/zenfs#199]
Why is "No valid superblock found" displayed after mkfs succeeds ?

$./plugin/zenfs/util/zenfs mkfs --zbd=nullb0 --aux_path=zenfs_log 
ZenFS file system created. Free space: 255552 MB

$ ./db_bench --fs_uri=zenfs://dev:nullb0 --benchmarks=fillrandom --use_direct_io_for_flush_and_compaction
Failed creating env: Invalid argument: NotFound: No valid superblock found: zenfs://dev:nullb0

$ ./plugin/zenfs/util/zenfs list --zbd=nullb0 --path=./.rocksdb
Failed to mount filesystem, error: NotFound: No valid superblock found

Linux version: 5.4.0-104-generic
Description: Ubuntu 20.04.4 LTS
RocksDB version: 7.3

**Comment by metaspace** [comment]
That is odd. Are you using memory backed null_blk?

cat /sys/kernel/config/nullb/features

Shoud contain memory_backed.

**Comment by lmc395319437** [comment]
> 
yes!I use null_blk.

$cat /sys/kernel/config/nullb/features
memory_backed,discard,bandwidth,cache,badblocks,zoned,zone_size

Seems to have memory backed!

**Comment by lmc395319437** [comment]
> 

Thanks！

I'm going to set memory backed to 1 and it's going to run!
