### ISSUE TITLE
fix unexpected extent length error

### ISSUE THREAD

**Issue by aravind-wdc** [westerndigitalcorporation/zenfs#203]
Have observed this below error message multiple times while running an OLTP workload on MyRocks + ZenFS stack and in parallel running zenfs utility commands.
`Failed to mount filesystem, error: IO error: Unexexpeted extent length while recovering`

Apart from the spelling typo, this error condidtion also needs fixing, it seems to be because of not locking files during a mount (from zenfs utility). Raising this issue to keep track of the bug.

**Comment by yhr** [comment]
We should probably avoid recovering files when mounting read-only like the utility does in these cases (as it the recovery assumes that the wp will not be moving around :))

**Comment by yhr** [comment]
This was fixed in 317c0eff28356ba2f0900d55e7f3c38b6ae891d2
