### ISSUE TITLE
Build system integration to Percona Server and TerarkDB

### ISSUE THREAD

**Issue by metaspace** [westerndigitalcorporation/zenfs#211]
Percona Server and TerarkDB are some times having issues when files are added or renamed in ZenFS repository. Percona build system is trying to scrape the ZenFS makefile for their CMake build while TerarkDB is hard coding the file names in their CMake build.

ZenFS should add a file list that is easily readable by CMake so that Percona Server and TerarkDB can stop breaking when ZenFS adds or removes files.

**Comment by metaspace** [comment]
#177 and #210 are affected by this

**Comment by metaspace** [comment]
#208 is affected as well

**Comment by yhr** [comment]
We have a cmakelist now, so the source file list is available for percona/terarkdb
