### ISSUE TITLE
Can't switch ZDB scheduler to mq-deadline to create ZenFS

### ISSUE THREAD

**Issue by ryderhsu0129** [westerndigitalcorporation/zenfs#220]
I have established the relevant environment to create ZenFS, using the mkfs command got some error :
`$./zenfs mkfs --zbd=nvme0n1 --aux_path=/usr/src/zenfs_temp`
_Failed to open zoned block device: nvme0n1, error: Invalid argument: Current ZBD scheduler is not mq-deadline, set it to mq-deadline._

but I can only set scheduler to mq-deadline on nvme0c0n1, nvme0n1 doesn't have the option :
`$cat /sys/block/nvme0n1/queue/scheduler `
_none_
`$cat /sys/block/nvme0c0n1/queue/scheduler`
_[mq-deadline] none_

then I specify --zbd argument to nvme0c0n1, and got another error :
`$./zenfs mkfs --zbd=nvme0c0n1 --aux_path=/usr/src/zenfs_temp`
_Failed to open zoned block device: nvme0c0n1, error: Invalid argument: Failed to open zoned block device for read: No such file or directory_

looks like the command doesn't recognize the ZBD device, 
how should i solve it?thanks!

**Comment by yhr** [comment]
@ryderhsu0129 : Thanks for reporting, we're digging into the cause of this

**Comment by yhr** [comment]
What kernel version are you using?

**Comment by ryderhsu0129** [comment]
@yhr
my kernel version is 5.10.32.

If I disable multipath by adding nvme-core.multipath=NO to grub file,
then  I have the scheduler mq-deadline option in the sysfs node :
`$cat /sys/block/nvme0n1/queue/scheduler`
_[mq-deadline] none_
I can create ZenFS success after doing the above action.

Is it not possible to create a ZenFS with the multipath function turned on?

**Comment by ryderhsu0129** [comment]
@yhr 
ok i got it, thanks for your reply.
