### ISSUE TITLE
Fix segfault on master with RocksDB 6.29.fb

### ISSUE THREAD

**Issue by MaisenbacherD** [westerndigitalcorporation/zenfs#233]
Change of `util: Fix occurances where back() might be called on an empty string` for `zenfs_tool_backup()` uncovered this issue.
test/utils/0040_backup.sh segfaults when building ZenFS with RocksDB 6.29.fb (c++11), therefore RocksDB nightly does not pass anymore.

This here might just be a workaround:
https://github.com/MaisenbacherD/zenfs/commit/f73efe148eb54d5117ba0d0d1da554f9e96869e6

We need to find a proper solution.

**Comment by yhr** [comment]
Fixed!
