### ISSUE TITLE
MTR tests fail

### ISSUE THREAD

**Issue by metaspace** [westerndigitalcorporation/zenfs#236]
Our weekly `mtr` tests are broken because we use a version of `percona-server` that does not support building `zenfs` with the `CMakeLists.txt` fragment.

We have a patch queued for `percona-server` to fix this issue. When that patch is applied, we update the version of `percona-server` we use for testing, and things should work again.

**Comment by metaspace** [comment]
Related to #211

**Comment by yhr** [comment]
fixed
