### ISSUE TITLE
garbage collection test data

### ISSUE THREAD

**Issue by attack204** [westerndigitalcorporation/zenfs#245]
Is the garbage collection test script available? I want to know the SST file's size and Zone Size in the test. I can't get the same space amplification improvement in my test because I think the formula "(100 - GC_SLOPE * (GC_START_LEVEL - free_percent))" is really relative to those two factors.

**Comment by yhr** [comment]
@attack204 : A garbage collection test script is on my todo list. I set zone size = target file size when testing garbage collection, so you can try that.

**Comment by attack204** [comment]
That's really helpful! Thank you!
