### ISSUE TITLE
Will Zone::Finish cause device io?

### ISSUE THREAD

**Issue by attack204** [westerndigitalcorporation/zenfs#252]
I want to count the write amplification of ZenFS, so I need to calculate device io. 
One thing is not for sure that Zone::Finish will move the write pointer to the end, will this operation in the ZNS SSD layer cause write io? I mean it directly moves wp to the end or fills some invalid data?
And the same problem in Zone::Reset, will this cause device io before it moves wp to start?

**Comment by yhr** [comment]
It depends on controller implementation. Finishes may cause write amp on the drive, but necessarily so, same thing with resets on non-full zones.

**Comment by attack204** [comment]
That's really helpful. So I think I should count 2 write amplifications. One is count Finish/Reset io and the other is not.
