### ISSUE TITLE
question : how can i test modfication for ZenFS whether work or not ?

### ISSUE THREAD

**Issue by sg20180546** [westerndigitalcorporation/zenfs#255]
I'm researching for Zenfs, devising improved zone allocation and reset algorithm for it. Maybe i would contribute for this repository.
So what i want to know is, what Rocksdb Test code (or something else) should to be passed to certificate the algorithm would work properly ? what test should be passed to contribute the repository at least ?
i usually use db_bench for now, but i think db_bench would not guarentee the algorithm is strict.
thank you.

**Comment by yhr** [comment]
@sg20180546 : We are very happy to receive PRs!   There are tests available in https://github.com/westerndigitalcorporation/zenfs/tree/master/tests . Please run at least the smoke, util and quick performance test suites before you submit a Pull request. See this commit message for how to run the tests: https://github.com/westerndigitalcorporation/zenfs/commit/f3c30243f3e156640494e227b10b4f6b65b42796
