### ISSUE TITLE
Compilation terminated due to include "trace_replay/io_tracer.h"

### ISSUE THREAD

**Issue by kekeMemory** [westerndigitalcorporation/zenfs#259]
Excuse me, I modified the fs/zenfs code before and compiled it without any problems.
I ran the compile directive as usual:`DEBUG_LEVEL=0 ROCKSDB_PLUGINS=zenfs make -j48 db_bench install`
But, today I suddenly met this problem arose.
I did not fix other folder codes expect /fs/zenfs
I met the errors:
![20230222205547](https://user-images.githubusercontent.com/40992472/220613230-8928359d-34df-49f4-a57c-e806700107f8.jpg)

**Comment by MaisenbacherD** [comment]
Hi @kekeMemory,
That looks like a RocksDB related issue. Which commit of RocksDB did you check out?

**Comment by kekeMemory** [comment]
> 
Thanks,@MaisenbacherD,
I used 7.7.3 RocksDB always, and I can successfully compileing in the past, I never met this problem before.

**Comment by MaisenbacherD** [comment]
I just cloned RocksDB v7.7.3 with ZenFS master and could sucessfully build both.
Can you please check that your local RocksDB tree is matching with upstream v7.7.3? :)

**Comment by kekeMemory** [comment]
@MaisenbacherD Yes, I have checked my current local RocksDB tree is matching with upstream v7.7.3

**Comment by MaisenbacherD** [comment]
What are the exact commits of RocksDB and ZenFS you are trying to build?

**Comment by kekeMemory** [comment]
@MaisenbacherD `sudo DEBUG_LEVEL=0 ROCKSDB_PLUGINS=zenfs make -j48 db_bench install`

**Comment by kekeMemory** [comment]
@MaisenbacherD Thanks I install new rocksdb again, then it can work.
