### ISSUE TITLE
Hi, I emulate a nullblk0 and want to run a zenfs based on it, but there is an error

### ISSUE THREAD

**Issue by Lsgoose** [westerndigitalcorporation/zenfs#267]
+ DEV=nullb0
+ FUZZ=5
+ cat /sys/class/block/nullb0/queue/chunk_sectors
+ ZONE_SZ_SECS=262144
+ ZONE_CAP=134217728
+ BASE_FZ=127506841
+ WB_SIZE=255013682
+ TARGET_FZ_BASE=255013682
+ TARGET_FILE_SIZE_MULTIPLIER=2
+ MAX_BYTES_FOR_LEVEL_BASE=510027364
+ MAX_BACKGROUND_JOBS=8
+ MAX_BACKGROUND_COMPACTIONS=8
+ OPEN_FILES=16
+ echo deadline
+ ./plugin/zenfs/util/zenfs mkfs --zbd=nullb0 --aux_path=/tmp/zenfs_nullb0 --finish_threshold=0 --force
ZenFS file system created. Free space: 3596 MB
+ ./db_bench --fs_uri=zenfs://nullb0 --key_size=16 --value_size=800 --target_file_size_base=255013682 --write_buffer_size=255013682 --max_bytes_for_level_base=510027364 --max_bytes_for_level_multiplier=4 --use_direct_io_for_flush_and_compaction --num=1500000 --benchmarks=fillrandom,overwrite --max_background_jobs=8 --max_background_compactions=8 --open_files=16
Failed creating env: Invalid argument: Malformed URI: zenfs://nullb0

**Comment by yhr** [comment]
Hi!

Looks like you need to adjust the fs_uri parameter, the format is:

 --fs_uri=zenfs://dev:<blockdev>

**Comment by yhr** [comment]
@Lsgoose : Did you try modifying the fs_uri path?
