### ISSUE TITLE
error: zenfs.mk:37: *** Generating ZenFS version failed

### ISSUE THREAD

**Issue by zhoulening969** [westerndigitalcorporation/zenfs#269]
Hello gentlemen,
I got some errors about compiling source code. If only rocksdb is compiled, there is no problem, but adding the Zenfs plugin will result in an error. Please help me.
Thanks,
Eddy

OS INFO
Centos : 7.9.2009(core)
Kernel : 6.3.1-1.el7.elrepo.x86_64

ERRORS
[root@localhost rocksdb]# DEBUG_LEVEL=0 ROCKSDB_PLUGINS=zenfs make -j48 db_bench install
$DEBUG_LEVEL is 0
plugin/zenfs/zenfs.mk:37: *** Generating ZenFS version failed.
[root@localhost rocksdb]#

**Comment by yhr** [comment]
Thanks for reporting, i'll try to reproduce the issue.

**Comment by zhoulening969** [comment]
After investigation, I found that the value of $(. SHELLSTATUS) is abnormal, but the version. h file can be generated normally and its content is # define ZENFS_ VERSION "v2.1.0-57-gb04ca0c-dirty".

Then I annotated the following statement in zenfs.mk:
ifneq ($(.SHELLSTATUS),0)
$(error Generating ZenFS version failed)
endif

Make again, and an error is reported as follows:
[ root@localhost  rocksdb]# DEBUG_ LEVEL=0 ROCKSDB_ PLUGINS=zenfs make -j48 db_ bench install
$DEBUG_ LEVEL is 0
Makefile:286: *** pkg-config failed。 

My pkg-config version is 0.29.2 and gcc version is 11.3.0.

**Comment by MaisenbacherD** [comment]
Hi @zhoulening969,
This looks similar to the issue https://github.com/westerndigitalcorporation/zenfs/issues/101

What RocksDB and ZenFS commits are you trying to build?

**Comment by MaisenbacherD** [comment]
I also build the latest rocksdb (v8.1.1) + zenfs master without an issue on my system.

Are you able to reproduce that issue with a clean copy of rocksdb and zenfs?

**Comment by zhoulening969** [comment]
@yhr @MaisenbacherD I tried to replace the server's make and cmake versions with the latest versions available, and then the compilation was successful.
Thank you all the same! Best, Zhou
