### ISSUE TITLE
What if I want to modify I/O scheduler algorithm？

### ISSUE THREAD

**Issue by YummuyWang** [westerndigitalcorporation/zenfs#272]
Which part should I revise to adapt my algorithm.
I mean can I revise mq-deadline or how to modify I/O requests in zenfs？

**Comment by aravind-wdc** [comment]
I/O scheduler is part of the Linux kernel, modifying that is not recommended unless you know what you are doing. But nevertheless, you can modify it for your tests.
There are other I/O schedulers that the kernel provides, but for now, ZNS drives works only with the mq-deadline I/O scheduler.

**Comment by YummuyWang** [comment]
Do you mean block/mq-deadline.c in source code or whole files like blk-mq-<some thing>?

**Comment by sinparking** [comment]
you need to modify the linux kernel, that is not a part of zenfs or rocksdb or femu simulator
