### ISSUE TITLE
Why Deletefile() do not check open_for_wr_mtx_ lock(AcquireWRLock) ?

### ISSUE THREAD

**Issue by sg20180546** [westerndigitalcorporation/zenfs#277]
Maybe it may incur zone capacity (remainig) leak, If the file is migrated by garbage collection.

fs/fs_zenfs.cc
```
    if (GetFileNoLock(fname) == nullptr) {
      Info(logger_, "Migrate file not exist anymore.");
      zbd_->ReleaseMigrateZone(target_zone);
      break;
    }
```
In the code, if file is deleted or removed during GC, break the loop and call SyncFileExtents. But there is no code about substracting Zone->used_capacity_ of extents that is migrated but deleted .
```

    ext->start_ = target_start;
    ext->zone_ = target_zone;
    ext->zone_->used_capacity_ += ext->length_;
```

Maybe there should be corresponding operation of above operation.

**Comment by yhr** [comment]
If the file has been deleted, the file destructor releases all extents and subtracts the zone used capacity counts
