### ISSUE TITLE
I encountered the following problem while executing this command DEBUG_LEVEL=0 ROCKSDB_PLUGINS=zenfs make -j48 db_bench install

### ISSUE THREAD

**Issue by 1024cs** [westerndigitalcorporation/zenfs#295]
plugin/zenfs/fs/fs_zenfs.cc: In member function ‘rocksdb::IOStatus rocksdb::ZenFS::OpenWritableFile(const std::string&, const rocksdb::FileOptions&, std::unique_ptr<rocksdb::FSWritableFile>*, rocksdb::IODebugContext*, bool)’:
plugin/zenfs/fs/fs_zenfs.cc:836:87: error: invalid new-expression of abstract class type ‘rocksdb::ZonedWritableFile’
  836 |       result->reset(new ZonedWritableFile(zbd_, !file_opts.use_direct_writes, zoneFile));
      |                                                                                       ^
In file included from plugin/zenfs/fs/fs_zenfs.h:20,
                 from plugin/zenfs/fs/fs_zenfs.cc:9:
plugin/zenfs/fs/io_zenfs.h:194:7: note:   because the following virtual functions are pure within ‘rocksdb::ZonedWritableFile’:
  194 | class ZonedWritableFile : public FSWritableFile {
      |       ^~~~~~~~~~~~~~~~~
In file included from plugin/zenfs/fs/io_zenfs.h:24:
./include/rocksdb/file_system.h:1180:20: note:     ‘virtual uint64_t rocksdb::FSWritableFile::GetFileSize(const rocksdb::IOOptions&, rocksdb::IODebugContext*)’
 1180 |   virtual uint64_t GetFileSize(const IOOptions& /*options*/,
      |                    ^~~~~~~~~~~
plugin/zenfs/fs/fs_zenfs.cc:868:85: error: invalid new-expression of abstract class type ‘rocksdb::ZonedWritableFile’
  868 |     result->reset(new ZonedWritableFile(zbd_, !file_opts.use_direct_writes, zoneFile));
      |                                                                                     ^
make: *** [Makefile:2569: plugin/zenfs/fs/fs_zenfs.o] Error 1

**Comment by MaisenbacherD** [comment]
Hi @1024cs, thanks for reporting this.

You already closed this issue but just for reference if anybody else bumps into this issue:
The purely virtual `FSWritableFile::GetFileSize` is currently not implemented on the main branch.
There is a pending PR that fixes this issue https://github.com/westerndigitalcorporation/zenfs/pull/294/commits/2230e12c3d22faee65e5d9e2035c35e986e54efe
