### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by sqrtpineapple** [westerndigitalcorporation/zenfs#3]
when compiling with g++ 9.3.0 or 7 or 10,the following error occurs:
```
/usr/bin/ld: /tmp/cc9gG75J.o: in function `main':
zenfs.cc:(.text+0x266e): undefined reference to `google::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: zenfs.cc:(.text+0x2754): undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
/usr/bin/ld: /tmp/cc9gG75J.o: in function `__static_initialization_and_destruction_0(int, int)':
zenfs.cc:(.text+0x2a38): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/usr/bin/ld: zenfs.cc:(.text+0x2af5): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/usr/bin/ld: zenfs.cc:(.text+0x2b66): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: zenfs.cc:(.text+0x2be1): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/usr/bin/ld: zenfs.cc:(.text+0x2c52): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: zenfs] Error 1
```

When compiling with g++ 4.8 or 5,the different error occurs:
```
g++: error: unrecognized command line option ‘-faligned-new’
make: *** [Makefile:12: zenfs] Error 1
```

Which version of g++ should be chosen? 
Thanks a lot!

**Comment by yhr** [comment]
I use gcc 9.3.0 , but it looks like you have not installed gflags. If you're on ubuntu, try: sudo apt-get install libgflags-dev

**Comment by sqrtpineapple** [comment]
> 
> 
> I use gcc 9.3.0 , but it looks like you have not installed gflags. If you're on ubuntu, try: sudo apt-get install libgflags-dev

It seems like can’t link to gflags.I don't know why so I edit the Makefile (add -lgflags) 
thanks!

**Comment by sqrtpineapple** [comment]
`femu@fvm:~/rocksdb$ ./plugin/zenfs/util/zenfs mkfs --zbd=/dev/nvme0n1 --aux-path=./plugin/zenfs/log
Failed to open zoned block device: /dev/nvme0n1, error: Invalid argument: Failed to open zoned block device`

The mkfs command error.Excuse me,do you know why?

**Comment by aravind-wdc** [comment]
what kind of drive is nvme0n1, Is nvme0n1 a physical ZNS drive ?

**Comment by sqrtpineapple** [comment]
> 
> 
> what kind of drive is nvme0n1, Is nvme0n1 a physical ZNS drive ?

It's an emulating NVMe block device.

**Comment by yhr** [comment]
You probably don't have permission to write to the block device. try 
`sudo ./plugin/zenfs/util/zenfs mkfs --zbd=/dev/nvme0n1 --aux-path=./plugin/zenfs/log Failed to open zoned block device: /dev/nvme0n1, error: Invalid argument: Failed to open zoned block device`

**Comment by sqrtpineapple** [comment]
Had already tried,it doesn't work either.

**Comment by yhr** [comment]
what is the output of this?
`cat /sys/class/block/nvme0n1/queue/zoned`

**Comment by sqrtpineapple** [comment]
> 
> 
> what is the output of this?
> `cat /sys/class/block/nvme0n1/queue/zoned`

```

femu@fvm:~$ cat /sys/class/block/nvme0n1/queue/zoned
host-managed
```

**Comment by yhr** [comment]
@sqrtpineapple : Could you try with this branch? I've added more descriptive error messages: https://github.com/westerndigitalcorporation/zenfs/tree/staging

**Comment by sqrtpineapple** [comment]
```
root@fvm:/home/femu/rocksdb# ./plugin/zenfs/util/zenfs mkfs --zbd=nvme0n1 --aux-path=./plugin/zenfs/log
ZenFS file system created. Free space: 3712 MB
```
Changed the zbd path,then succeeded.Thanks!

**Comment by yhr** [comment]
Aaah, yeah, that is an easy mistake to make.

**Comment by ZhuWeiLin0** [comment]
> > I use gcc 9.3.0 , but it looks like you have not installed gflags. If you're on ubuntu, try: sudo apt-get install libgflags-dev
> 
> It seems like can’t link to gflags.I don't know why so I edit the Makefile (add -lgflags) thanks!
 
hello, i encountered the same problem. Could you kindly tell me how to exactly add this code ? thanks very much! @sqrtpineapple
