### ISSUE TITLE
[Feature Request] We need a better ZoneAllocation implementation

### ISSUE THREAD

**Issue by royguo** [westerndigitalcorporation/zenfs#36]
Background:
1. WAL sync should be enabled by default. 
2. Multiple WAL files may be opened at the same time (only one WAI file could be written into)
3. Over 14 files could be concurrently opened & written
4. WAL throughput could be larger than 150MB/s (We have KV-separation in TerarkDB, so you can lower down this in RocksDB)
5. Multiple column families (3~4 CFs)
6. Key 16B, value 8KB

Problems Description:
- WAL writes could be affected by other file writes, which leads to user side latency spike 

Expectations:
- All WAL writes should be returned ASAP, background writers can wait until there are free zone resources available.
- We should also make sure there's at least one free zone for random reading operation.
- Thus we should gurantee
  - 2+ WAL zones, 1 Random Read zones, 11- for others

**Comment by yhr** [comment]
Yes, this is something I've been thinking about as well. One solution i would like to try out is to prioritize wal writes by reserving at least one available(empty or zones without active writes) for wal allocation. Or perhaps even better, a configurable parameter that can tell zenfs that the user wants at least N MBs of WAL space. There will be backpressure eventually if the compaction can't keep up, but it should remove the latency spikes. 

I don't know what you mean by random read zone, all zones can be randomly read. Could you explain?

**Comment by royguo** [comment]
Hi, @yhr 

We've patched a simple solution for now:
- In previous version there is a big lock inside AllocateZone and do not aware of WAL writes and do not allow concurrent allocation at all
- We split the lock and allow normal writes to give up lock during the  Zone allocation to WAL Zone allocation (carefully tuned)
- Now the WAL latency works good and we will submit the PR soon to see if its possible for you to merge into your repo,
- But for long term purpose, we do need to move the allocation to background thread but its too complex for us since we don't know ZenFS as weel as you guys.

For the random read question:
- Anytime we need to read a zone, that zone should be implicitly opened, right? thus it could take an open zone resource, correct me if I was wrong, thanks.

**Comment by royguo** [comment]
Besides that, we also find that the RocksDB does not close WAL files explicitly by default, which may take too many open zone resources during a heavy workload benchmarking.

In our case, we find there are almost 6~7 WALs were opened at the same time(though only one file is able to be written), the other WAL files keep opening there until RocksDB Sync/Close them in the background. 

But this is not the first priority, we handled it by some hack fix in RocksDB/TerarkDB for now.

**Comment by skyzh** [comment]
FYI, this is one of our attempts to reduce allocation latency. https://github.com/bzbd/zenfs/pull/19

**Comment by yhr** [comment]
My plan is to do this work in three steps:

1. Refactor the allocator function, separating the zone management and allocation functionality (the allocator would then just pick from a list of available zones, or wait if there are none at the moment)
2. Move zone management(resets, finishes) to a background thread  - fixing the latency problem 
3. Add WAL allocation prioritization (keep N zones in the available list for WALs)

**Comment by yhr** [comment]
The allocator has been reworked as part of https://github.com/westerndigitalcorporation/zenfs/pull/114 , closing this :)
