### ISSUE TITLE
Why do we need `Sync()` in `Zone::Append()` ?

### ISSUE THREAD

**Issue by royguo** [westerndigitalcorporation/zenfs#39]
https://github.com/westerndigitalcorporation/zenfs/blob/4f577cd4d4bf4b40b65ecd8b8680f37dc7b7780c/fs/zbd_zenfs.cc#L151-L160

Why do we need to Sync() here in a synchronize `Append()` method? Isn't it true that a successful `pwrite` guarantees data persistency?

**Comment by yhr** [comment]
This is done in the experimental branch to ensure we won't exceed more than one outstanding write. We could increase the number of buffers / queue depth if needed, but having async buffer flushes(one background write) improved things considerably so its probably not motivated.

**Comment by yhr** [comment]
@royguo : Can we close this?
