### ISSUE TITLE
Do we really need a lock inside `ZonedWritableFile::Fsync`?

### ISSUE THREAD

**Issue by royguo** [westerndigitalcorporation/zenfs#45]
```
IOStatus ZonedWritableFile::Fsync(const IOOptions& /*options*/,
                                  IODebugContext* /*dbg*/) {
  IOStatus s;

  buffer_mtx_.lock();
  s = FlushBuffer();
  buffer_mtx_.unlock();
  if (!s.ok()) {
    return s;
  }
  zoneFile_->PushExtent();

  return metadata_writer_->Persist(zoneFile_);
}
```

We know these facts about RocksDB:
- Single thread writing
- No file reading if a file is not closed
  - for WAL maybe there's a tiny possibility some applications want to re-use WAL, but I think we should let RocksDB handle data consistency

**Comment by yhr** [comment]
@royguo : see https://github.com/facebook/rocksdb/blob/e8a700115990ebec5dddc2ffac54d9af41e9ca69/include/rocksdb/file_system.h#L898 . To support mysql/myrocks/zenfs fsyncs must be thread safe

**Comment by yhr** [comment]
@royguo : I'll close this if you have no further questions? thanks!
