### ISSUE TITLE
support for BLKCLOSEZONE should be required

### ISSUE THREAD

**Issue by inikep** [westerndigitalcorporation/zenfs#66]
The latest Ubuntu 20.04.3 LTS has kernel 5.11 but only linux-libc-dev version (5.4.0-89.100) what means that blkzoned.h is from 5.4 and doesn't support BLKCLOSEZONE.
IMHO it doesn't make sense to compile `zenfs` without BLKCLOSEZONE because it doesn't work correctly. It would be better to stop configure or building with an error message that blkzoned.h from 5.5+ is required.

@damien-lemoal wrote:
Zenfs can trivially check for that on startup by trying to open+close a full or empty zone (that is a no-op normally). If zenfs sees an ENOSUP error from libzbd, then a badly compiled version of libzbd is being used and zenfs can warn the users. Again, nothing wrong with libzbd here. zenfs should handle this issue, and a build problem reported to Ubuntu. Distros normally rebuild all packages that have an uapi dependency against newer kernels. The libzbd .deb packaging definitions may have a problem (that is not maintained in libzbd project, eventhough that is synced from time to time).

**Comment by metaspace** [comment]
Closing this as it was fixed by westerndigitalcorporation/libzbd@126eaa2.
