### ISSUE TITLE
db_stress failure

### ISSUE THREAD

**Issue by aravind-wdc** [westerndigitalcorporation/zenfs#72]
db_stress fails with following error:

sudo ./db_stress --ops_per_thread=1000 --reopen=5 --fs_uri=zenfs://dev:nvme2n2

WARNING: prefix_size is non-zero but memtablerep != prefix_hash
DB path: [rocksdbtest/dbstress]
(Re-)verified 0 unique IDs
Error opening unique id file for append: IO error: No such file or directory: While open a file for appending: rocksdbtest/dbstress/.unique_ids: No such file or directory
Choosing random keys with no overwrite
Creating 2621440 locks
Starting continuous_verification_thread
2021/10/28-11:47:57  Initializing worker threads
2021/10/28-11:47:57  Starting database operations
2021/10/28-11:47:57  Reopening database for the 1th time
WARNING: prefix_size is non-zero but memtablerep != prefix_hash
DB path: [rocksdbtest/dbstress]
Segmentation fault

Probably due to https://github.com/facebook/rocksdb/pull/8990
and 0534393fc889e6dc44eb69d89fd2385082b4bddb

**Comment by yhr** [comment]
fixed upstream, closing
