### ISSUE TITLE
Header file updates does not trigger zenfs object files to rebuild

### ISSUE THREAD

**Issue by yhr** [westerndigitalcorporation/zenfs#73]
For some reason, updates to header files require a clean rebuild to propagate. This can manifest in very hard-to-debug issues if one forgets to do a clean rebuild.

It looks like rocksdb is supporting the -mm header file dependency handling, but this might be broken for plugins.

**Comment by MaisenbacherD** [comment]
Pull request for RocksDB was submitted:
https://github.com/facebook/rocksdb/pull/9120

**Comment by MaisenbacherD** [comment]
Also submitted pull request for ZenFS to ignore the dependency files:
https://github.com/westerndigitalcorporation/zenfs/pull/77

**Comment by yhr** [comment]
all done!
