### ISSUE TITLE
ZenFS Version

### ISSUE THREAD

**Issue by MaisenbacherD** [westerndigitalcorporation/zenfs#80]
In order to identify the ZenFS version, that is being run on a specific instance, we need to introduce a semiautomatic versioning mechanism.
A new utils command (fs-info) should report and store the ZenFS version in the superblock struct in addition to the on-disk format version.
On filesystem creation the ZenFS version should be reported.

**Comment by MaisenbacherD** [comment]
Submitted PR https://github.com/westerndigitalcorporation/zenfs/pull/94

**Comment by MaisenbacherD** [comment]
After the pull request is merged a PR for percona-server with this branch has to be submitted: https://github.com/MaisenbacherD/percona-server/tree/zenfs-version

**Comment by MaisenbacherD** [comment]
PR #94 was merged.
Submitted PR for percona-server: https://github.com/percona/percona-server/pull/4555

**Comment by yhr** [comment]
Merged in percona-server
