### ISSUE TITLE
Enable logging for libzbd in debug builds

### ISSUE THREAD

**Issue by metaspace** [westerndigitalcorporation/zenfs#84]
We can enable more logging in libzbd (printfs to stdout/sterr) when setting up a zbd inside zenfs.

**Comment by indraneel-m** [comment]
@metaspace , can you elaborate a bit here? The ticket is for adding additional logging in libzbd or improved logging of the responses returned by libzbd to zenfs?

**Comment by metaspace** [comment]
`libzbd` has internal logging infrastructure. It is disabled by default. The user of the library needs to call a setup function to enable logging. We had bugs earlier that would have been made visible by enabling error level logging in libzbd, so it is probably a good idea to do so.

**Comment by yhr** [comment]
closed as it turned out impractical, see #171
